blueprint:
  name: Opened doors alert
  description: Notify when doors are opened
  domain: automation
  input:
    door_sensor:
      name: Door Sensor
      description: This sensor will detect if door are closed/opened
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: door
    notification_target:
      name: Notification Target
      description: Name of the `notify.*` action
    alert_delay:
      name: Alert Delay
      description: How long to wait before sending notification
      default: "00:05:00"
      selector:
        duration: {}
    door_name:
      name: Door Name
      description: Name of the door (will be used in notifications)
      selector:
        text: {}
triggers:
- trigger: state
  entity_id: !input door_sensor
  from: 'off'
  to: 'on'
  for: !input alert_delay
conditions: []
actions:
- variables:
    tag: '{{ ''TAG_door_alert_'' ~ context.id }}'
    action_ack: '{{ ''ACK_door_alert_'' ~ context.id }}'
    door_name: !input door_name
- action: !input notification_target
  data:
    title: '🚪 Alert'
    message: '❌ {{ door_name }} są otwarte!'
    data:
      tag: '{{ tag }}'
      actions:
      - action: '{{ action_ack }}'
        title: Ignoruj
- wait_for_trigger:
  - trigger: state
    entity_id: !input door_sensor
    to: 'off'
  - trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: '{{ action_ack }}'
- condition: state
  entity_id: !input door_sensor
  state: 'off'
- action: !input notification_target
  metadata: {}
  data:
    title: '🚪 Alert'
    message: '✅ {{ door_name }} są zamknięte'
    data:
      tag: '{{ tag }}'
mode: single

